require("dotenv").config();
const express = require("express");
const cors = require("cors");
const connectDB = require("./database/db");
const authRoutes = require("./routes/authRoutes");
const courseRoutes = require("./routes/courseRoutes");
const app = express();
app.use(cors());
app.use(express.json());
app.use("/uploads", express.static("uploads"));
connectDB();
app.get("/", (req,res)=>res.send("API is working"));
app.use("/api/auth", authRoutes);
app.use("/api/courses", courseRoutes);
const PORT=process.env.PORT||5600;
app.listen(PORT,()=>console.log(`Server running on port ${PORT}`));
